---
label: Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: field_group
    name: header
    label: Header Configuration
    fields:
      - type: text
        name: logo
        label: Header Logo Text
        description: The Logo Text in the upper left corner of the page (may contain HTML)
        config:
          required: true
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
      - type: text
        name: title
        label: Footer Title
        description: The title displayed at the top of the left footer section
      - type: textarea
        name: subtitle
        label: Footer Subtitle
        description: The text displayed below the footer title
        config:
          wysiwyg: true
          schema:
            format: markdown
      - type: field_group_list
        name: social_links
        label: Social Media
        description: A list of social media links
        config:
          labelField: title
        fields:
          - type: text
            name: title
            label: Title
          - type: text
            name: icon
            label: Icon
            description: Font Awesome icon
          - type: text
            name: link_url
            label: URL
      - type: field_group
        name: ref_list1
        label: First References List
        fields:
          - type: include
            name: include_ref_list
            label: Include ref_list
            template: ref_list
      - type: field_group
        name: ref_list2
        label: Second References List
        fields:
          - type: include
            name: include_ref_list
            label: Include ref_list
            template: ref_list
      - type: field_group
        name: contact
        label: Contact Configuration
        fields:
          - type: boolean
            name: enabled
            label: Enabled
            description: Displays the Section in the site footer
            default: false
          - type: text
            name: title
            label: Contact Section Title
          - type: textarea
            name: subtitle
            label: Contact Section Subtitle
            config:
              wysiwyg: true
              schema:
                format: markdown
          - type: text
            name: phone
            label: Phone Number
          - type: text
            name: phone_link
            label: Phone Number URL
            description: The URL tied to the phone number
      - type: text
        name: copyright
        label: Copyright Text
        description: The copyright text displayed at the bottom of the footer
  - type: select
    name: palette
    label: Color Palette
    description: The color pallete used for the site
    config:
      required: true
      source:
        type: custom
      options:
        - blue
        - green
